#https://twitchtokengenerator.com/
[database]
password = "your_database_password"
[twitch]
api_client_id = "your_api_client_id"
api_client_secret = "your_api_client_secret"
api_refresh_token = "your_api_refresh_token"
chatbot_username = "your_twitch_username"
chatbot_access_token = "your_twitch_access_token"
[vk_video_live]
api_client_id = "your_api_client_id"
api_client_secret = "your_api_client_secret"