#https://id.twitch.tv/oauth2/authorize?response_type=code&client_id=<client_id>&redirect_uri=http://localhost
[twitch.api]
client_id = "your_client_id"
client_secret = "your_client_secret"
code = "your_code"
access_token="your_access_token"
refresh_token="your_refresh_token"
#https://twitchtokengenerator.com/
[twitch.chat]
username = "your_twitch_username"
access_token = "your_twitch_access_token"
channel = "your_twitch_channel"
#На всякий случай сохраним
client_id = "your_twitch_client_id"
refresh_token = "your_twitch_refresh_token"
[vk_video_live.chat]
channel = "your_vkvideolive_channel"
[vk_video_live.api]
client_id = "your_vkvideolive_client_id"
client_secret = "your_vkvideolive_client_secret"
access_token = "your_vkvideolive_access_token"